spring:
  application:
    name: tutor

  datasource:
    url: jdbc:postgresql://localhost:5432/EduSyncDB
    username: postgres
    password: sshs1sshs!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create  # 최초 실행시에만 create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_schema: public
    defer-datasource-initialization: true
    generate-ddl: true

# 인코딩 설정
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

# 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.edusync.tutor: DEBUG
    org.edusync: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

jwt:
  secret: yourSecretKey
  expiration: 86400000  # 24시간

mvc:
  static-path-pattern: /static/**
  pathmatch:
    matching-strategy: ant_path_matcher

web:
  resources:
    static-locations: classpath:/static/
    add-mappings: true

  sql:
    init:
      mode: always
  jwt:
    secret: eduedu1234 # JWT 암호화 키