spring:
  application:
    name: tutor

  # H2 Database 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console 설정
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # 외부 접속 허용

  # JPA 설정
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  # Security 설정 완전 비활성화
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuator.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

  # Security 설정
  security:
    basic:
      enabled: false
    user:
      name: none
      password: none

  # Jackson 설정
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

# 인코딩 설정
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

# 로깅 설정
logging:
  level:  
    root: INFO
    org.springframework.web: INFO
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.edusync.tutor: DEBUG
